apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-entrypoint
  namespace: logging
data:
  fluent-bit-entrypoint.sh: |
    #!/bin/sh
    envsubst < /fluent-bit/etc/fluent-bit.conf > /tmp/fluent-bit.conf
    exec /fluent-bit/bin/fluent-bit -c /tmp/fluent-bit.conf
