apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-init-first: "true"
        vault.hashicorp.com/role: "postgres-auth-role"
        vault.hashicorp.com/agent-inject-secret-db.env: "kv/data/postgres-auth"
        vault.hashicorp.com/agent-inject-vault-addr: "http://external-vault.default.svc.cluster.local:8200"
        vault.hashicorp.com/agent-inject-template-db.env: |
          {{- with secret "kv/data/postgres-auth" -}}
          POSTGRES_USER={{ .Data.data.DB_USER_DEFAULT }}
          POSTGRES_PASSWORD={{ .Data.data.POSTGRES_PASSWORD }}
          POSTGRES_DB={{ .Data.data.DB_NAME_AUTH }}
          DB_ADMIN_PASSWORD={{ .Data.data.DB_ADMIN_PASSWORD }}
          DB_APP_USER_PASSWORD={{ .Data.data.DB_APP_USER_PASSWORD }}
          {{- end }}
    spec:
      serviceAccountName: postgres-auth-sa
      containers:
        - name: postgres
          image: postgres:16.3
          ports:
            - containerPort: 5432
          command: ["/bin/bash", "-c"]
          args:
            - |
              export $(cat /vault/secrets/db.env | xargs)
              exec docker-entrypoint.sh postgres
          volumeMounts:
            - name: postgres-pvc-auth
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc-auth
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
